### ISSUE TITLE
Support Github Action

### ISSUE THREAD

**Issue by azzamsa** [zyedidia/eget#104]
Hi, 👋🏽 

Any plan to support GitHub action?
Something like [jaxxstorm/action-install-gh-release: GitHub Action to install the Github Release binaries](https://github.com/jaxxstorm/action-install-gh-release).

```yml
# ...
steps:
  - name: Install typst
    uses: zyedidia/eget-action@v1
    with: 
      repo: typst/typst
      to: ~/.local/bin
```
