### ISSUE TITLE
Issue with Repository

### ISSUE THREAD

**Issue by zQueal** [zyedidia/eget#112]
This is my config;

```toml
["BurntSushi/ripgrep"]
  asset_filters = ["pc-windows-gnu", "^sha256"]
  target = "C:\\Utilities\\exe\\rg.exe"
```

Running `eget --download-all` gets me this;

```cli
Downloading 100% [==================================================================================================] (10/10 MB, 31.540 MB/s)
sha256sum (SHA256 hash of ripgrep-14.1.1-x86_64-pc-windows-gnu.zip:
01469c43c3fffdb4baff80469a75a7bf1dc3d0bf4ef63cda72a22f885f27465a
CertUtil: -hashfile command completed successfully.
) too small: 0 bytes decoded
```

Worked perfectly fine until this last release. 🤷🏻‍♂️
