### ISSUE TITLE
Case sensitivity for repo names in eget.toml

### ISSUE THREAD

**Issue by starfishpatkhoo** [zyedidia/eget#119]
I accidentally copy-pasted the wrong thing, and stumbled upon this.. Not a big deal, but probably a good FYI or such. 😄 

```toml
[global]
download_only = true

["VSCodium/vscodium"]
asset_filters = ["^.sha1", "win32-x64", ".zip"]
```

If you executed `eget VSCodium/vscodium` then the asset filter is applied, but if you did `eget vscodium/vscodium` instead, then the asset filter is ignored (but downloading still works)...

PS. This is eget v1.3.4
