### ISSUE TITLE
Feature: Add instructions for maintainers

### ISSUE THREAD

**Issue by beatbrot** [zyedidia/eget#3]
It would be great to add instructions for maintainers on how to structure releases to be perfectly compatible with eget.

I, myself would love to support eget as a stupidly simple one-line install. But I dont see what I need to change to make this happen. Some documentation would be great!

Also, as a sidenote: How did you create the GIF in the readme?

**Comment by zyedidia** [comment]
I just added some docs at https://github.com/zyedidia/eget/blob/master/DOCS.md. Will expand it some more later.

I used terminalizer to render the gif in the readme. I can send you the settings I used if you are curious.

**Comment by beatbrot** [comment]
Thanks so much! That is exactly what I wanted!

Also, I really would like to have your settings :) Just send them to me at loy.christoph@gmail.com

**Comment by zyedidia** [comment]
Here is the terminalizer config (most things are left default) I used in the recording file:

```yaml
config:
  command: bash -l
  cwd: /home/zyedidia/demo
  env:
    recording: true
  cols: 80
  rows: 10
  repeat: 0
  quality: 50
  frameDelay: auto
  maxIdleTime: 2000
  frameBox:
    type: solid
    style:
      border: 0px black solid
      # boxShadow: none
      # margin: 0px
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  cursorStyle: block
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  fontSize: 12
  lineHeight: 1
  letterSpacing: 0
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"

records:
    # ...
```
