### ISSUE TITLE
[Request] Provide Binaries for Android

### ISSUE THREAD

**Issue by Azathothas** [zyedidia/eget#92]
An example action.yaml
```yaml
      - name: Build eget for arm64-v8a (Native)
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #Get Source
          pushd $(mktemp -d) && git clone "https://github.com/zyedidia/eget" && cd eget
          # android 29 --> Android 10.0 or Later
          # ANDROID_NDK = /usr/local/lib/android/sdk/ndk/
          export CC="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang"
          export CXX="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++"
          #Compile
          # CGO_ENABLED must be enabled to use android native libs, else things like dns etc won't work
          # Binaries compiled this way are always dynamically linked to /system/bin/linker64
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -v -ldflags="-s -w"
          #meta 
          file "./eget"
```

- #### Why ?
Using **`eget-xxx-linux_arm64.tar.gz`** 
![image](https://github.com/zyedidia/eget/assets/58171889/b7b4ed4e-fa45-4ddf-9374-6047d0cf4c50)

But after compiling with abv step,
![image](https://github.com/zyedidia/eget/assets/58171889/0aa907fb-ebde-4e2b-abd9-cbac976b3c63)
