### ISSUE TITLE
Fetch more than one archive from a repository?

### ISSUE THREAD

**Issue by lwbt** [zyedidia/eget#98]
I have the following configuration:

```toml
[global]
    upgrade_only = true

["ahmetb/kubectx"]
    asset_filters = [ "linux", ".tar.gz" ]
    all = true
    file = "kube*"
    target = "~/.local/bin/"
```

https://github.com/ahmetb/kubectx/releases

`file = "kube*"` should extract `kubectx` and `kubens` into `~/.local/bin/`.

But instead I get this:

```bash
eget --download-all
2 candidates found for asset chain: please select manually
(1) kubectx_v0.9.5_linux_x86_64.tar.gz
(2) kubens_v0.9.5_linux_x86_64.tar.gz
Enter selection number: Error reading selection
one or more errors occurred while downloading: [exit status 1]
```

Am I interpreting https://github.com/zyedidia/eget/issues/15 wrong and it does not address my issue?

I wouldn't mind doing this instead:

```toml
["ahmetb/kubectx"]
    asset_filters = [ "kubectx", "linux", ".tar.gz" ]
    file = "kubectx"
    target = "~/.local/bin/"
["ahmetb/kubectx"]
    asset_filters = [ "kubens", "linux", ".tar.gz" ]
    file = "kubectx"
    target = "~/.local/bin/"
```

But it looks like eget fails to parse the file and immediately exits. Which I would consider another bug, it should tell a user that the file is not valid.

**Comment by cj81499** [comment]
I'm having a similar issue with https://github.com/bazelbuild/buildtools. I want to install both `buildifier` and `buildozer` (I don't personally care about `unused_deps`, although I could imagine someone wanting to install that too).

---

> eget fails to parse the file

That makes sense, since that's not valid toml.

I propose using a config "syntax" like the following. This would mean that `eget` must handle either a [table](https://toml.io/en/v1.0.0#table) _or_ an [array of tables](https://toml.io/en/v1.0.0#array-of-tables) at the "top level" of the config file.

```toml
[["bazelbuild/buildtools"]]
asset_filters = ["buildifier"]

[["bazelbuild/buildtools"]]
asset_filters = ["buildozer"]
```

For people unfamiliar with `toml`, the equivalent `json` is:

```json
{
  "bazelbuild/buildtools": [
    {
      "asset_filters": [
        "buildifier"
      ]
    },
    {
      "asset_filters": [
        "buildozer"
      ]
    }
  ]
}
```
